# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb023e21597a87da5bbbba822e2b608679d4d7744cf5e341d208001260e0e51c578b512dac7d46acceacba631756672ffd5ca4693486e310cae7ac7b2c0bf855

test:
  secret_key_base: d790810325687d1183f41169c8e7239ccfe8976f0093fa96ed6d71ebb143b8869bbbf6543eacc0521499eb324a171bb4ef2a4fca2447e6901660d993799e3d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
